# Generated by Django 5.1.5 on 2025-02-19 15:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="InsuredPerson",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("first_name", models.CharField(max_length=50)),
                ("last_name", models.CharField(max_length=50)),
                ("age", models.IntegerField()),
                ("phone", models.CharField(max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name="Insurance",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "insurance_type",
                    models.CharField(
                        choices=[
                            ("life", "Životní pojištění"),
                            ("travel", "Cestovní pojištění"),
                            ("property", "Majetkové pojištění"),
                        ],
                        max_length=20,
                    ),
                ),
                ("duration_years", models.IntegerField()),
                (
                    "insured_person",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="insurance.insuredperson",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="SubInsurance",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("price", models.IntegerField()),
                (
                    "insurance",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="insurance.insurance",
                    ),
                ),
            ],
        ),
    ]
