# Generated by Django 5.1.5 on 2025-02-19 16:24

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("insurance", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="insuredperson",
            name="age",
        ),
        migrations.AddField(
            model_name="insuredperson",
            name="birth_date",
            field=models.DateField(blank=True, null=True),
        ),
    ]
