# Generated by Django 5.1.5 on 2025-03-17 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('insurance', '0002_remove_insuredperson_age_insuredperson_birth_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='insuredperson',
            name='phone',
            field=models.CharField(max_length=9),
        ),
    ]
